#!/usr/bin/bash

# Set wallpaper
BG_IMAGE_PATH=~/pictures/wallpaper.jpg
if [ -f $BG_IMAGE_PATH ]; then
	feh --bg-center --bg-fill $BG_IMAGE_PATH
fi

# Set keyboard layout
setxkbmap us -variant intl

# Run conky
CONKY_CONFIGS_PATH=$HOME/.config/conky/
killall -q conky
for CONKY_CONFIG in $CONKY_CONFIGS_PATH/*; do
	conky -c $CONKY_CONFIG &
done
