#!/usr/bin/bash

# Display external by default
if xrandr | grep "HDMI-A-0 connected"; then
	xrandr --output eDP --off
	xrandr --newmode "1360x768" 84.75 1360 1432 1568 1776 768 771 781 798 -hsync +vsync
	xrandr --addmode HDMI-A-0 "1360x768"
	xrandr --output HDMI-A-0 --mode "1360x768"
fi

# Set wallpaper
BG_IMAGE_PATH=~/Pictures/wallpaper.jpg
if [ -f $BG_IMAGE_PATH ]; then
	feh --bg-center --bg-fill $BG_IMAGE_PATH
fi

# Set keyboard layout
setxkbmap us -variant intl
