#!/usr/bin/bash

CANCEL="ﰸ  Cancel"
LOGOUT="  Logout"
REBOOT="累  Reboot"
POWER_OFF="襤  Power off"
OPT=$(echo -e "$CANCEL\n$LOGOUT\n$REBOOT\n$POWER_OFF" | dmenu -i -p "Power")

if [ "$OPT" = "$LOGOUT" ]; then
	pkill -u $USER
elif [ "$OPT" = "$REBOOT" ]; then
	reboot
elif [ "$OPT" = "$POWER_OFF" ]; then
	poweroff
fi
