#!/usr/bin/bash

OPT=$(echo -e "Cancel\nLogout\nReboot\nPower off" | dmenu -i -p "Power")

if [ "$OPT" = "Logout" ]; then
	logout
elif [ "$OPT" = "Reboot" ]; then
	reboot
elif [ "$OPT" = "Power off" ]; then
	poweroff
fi




