#!/usr/bin/bash

DEFAULT_MONITOR="HDMI-A-0"
EXTERNAL_MONITOR="eDP"

EXT_ONLY="EXTERNAL ONLY"
DFT_ONLY="DEFAULT ONLY"
BOTH="BOTH"

OPTS=`echo "$EXT_ONLY;$DFT_ONLY;$BOTH" | tr ';' '\n'`
SEL=`echo "$OPTS" | dmenu`

if [ "$SEL" = "$DFT_ONLY" ]; then
	xrandr --output $DEFAULT_MONITOR --off --output $EXTERNAL_MONITOR --auto
elif [ "$SEL" = "$EXT_ONLY" ]; then
	xrandr --output $EXTERNAL_MONITOR --off --output $DEFAULT_MONITOR --auto
elif [ "$SEL" = "$BOTH" ]; then
	xrandr --output $DEFAULT_MONITOR --auto --output $EXTERNAL_MONITOR --auto --right-of $DEFAULT_MONITOR
fi
